### ISSUE TITLE
Could not parse device path: Invalid Argument

### ISSUE THREAD

**Issue by oxr463** [rhboot/efibootmgr#133]
The following command fails to parse the boot entries:

```sh
efibootmgr -v
```

Instead it returns the following error:

```sh
Could not parse device path: Invalid Argument.
```

See: https://bugs.launchpad.net/ubuntu/+source/efivar/+bug/1844320, https://bugzilla.redhat.com/show_bug.cgi?id=1773175

**Comment by ncopa** [comment]
This is a problem in https://github.com/rhboot/efivar and fixed in commit https://github.com/rhboot/efivar/commit/4e04afc2df9bbc26e5ab524b53a6f4f1e61d7c9e

See: https://github.com/rhboot/efivar/issues/127#issuecomment-632575794

**Comment by mimi89999** [comment]
Hello,
I applied both patches and still had the same issue. Then I built latest master of efibootmgr and efivar. Still the same.
```
root@s217-lab00:~# /dev/shm/efibootmgr/src/efibootmgr -v
BootCurrent: 0003
Timeout: 2 seconds
BootOrder: 0003,0004,0005,000A,0007,0008,0009,0002
Boot0000* Windows Boot ManagerCould not parse device path: Invalid argument
error trace:
 /build/efivar-yvRv8P/efivar-37/src/include/efivar/efivar-dp.h:1208 efidp_is_valid(): invalid device path node type: Invalid argument
Boot0002  winCould not parse device path: Invalid argument
error trace:
 /build/efivar-yvRv8P/efivar-37/src/include/efivar/efivar-dp.h:1208 efidp_is_valid(): invalid device path node type: Invalid argument
root@s217-lab00:~# /dev/shm/efivar/src/efivar -n 8be4df61-93ca-11d2-aa0d-00e098032b8c-Boot0000 -p
GUID: 8be4df61-93ca-11d2-aa0d-00e098032b8c
Name: "Boot0000"
Attributes:
	Non-Volatile
	Boot Service Access
	Runtime Service Access
Value:
00000000  01 00 00 00 74 00 57 00  69 00 6e 00 64 00 6f 00  |....t.W.i.n.d.o.|
00000010  77 00 73 00 20 00 42 00  6f 00 6f 00 74 00 20 00  |w.s. .B.o.o.t. .|
00000020  4d 00 61 00 6e 00 61 00  67 00 65 00 72 00 00 00  |M.a.n.a.g.e.r...|
00000030  04 01 2a 00 01 00 00 00  00 08 00 00 00 00 00 00  |..*.............|
00000040  00 40 06 00 00 00 00 00  d8 bc 3b 78 7d 13 4f 20  |.@........;x}.O |
00000050  a4 da ac 0a 68 fd dc aa  02 02 04 04 46 00 5c 00  |....h.......F.\.|
00000060  45 00 46 00 49 00 5c 00  4d 00 69 00 63 00 72 00  |E.F.I.\.M.i.c.r.|
00000070  6f 00 73 00 6f 00 66 00  74 00 5c 00 42 00 6f 00  |o.s.o.f.t.\.B.o.|
00000080  6f 00 74 00 5c 00 62 00  6f 00 6f 00 74 00 6d 00  |o.t.\.b.o.o.t.m.|
00000090  67 00 66 00 77 00 2e 00  65 00 66 00 69 00 00 00  |g.f.w...e.f.i...|
000000a0  7f ff 04 00 57 49 4e 44  4f 57 53 00 01 00 00 00  |....WINDOWS.....|
000000b0  88 00 00 00 78 00 00 00  42 00 43 00 44 00 4f 00  |....x...B.C.D.O.|
000000c0  42 00 4a 00 45 00 43 00  54 00 3d 00 7b 00 39 00  |B.J.E.C.T.=.{.9.|
000000d0  64 00 65 00 61 00 38 00  36 00 32 00 63 00 2d 00  |d.e.a.8.6.2.c.-.|
000000e0  35 00 63 00 64 00 64 00  2d 00 34 00 65 00 37 00  |5.c.d.d.-.4.e.7.|
000000f0  30 00 2d 00 61 00 63 00  63 00 31 00 2d 00 66 00  |0.-.a.c.c.1.-.f.|
00000100  33 00 32 00 62 00 33 00  34 00 34 00 64 00 34 00  |3.2.b.3.4.4.d.4.|
00000110  37 00 39 00 35 00 7d 00  00 00 31 00 01 00 00 00  |7.9.5.}...1.....|
00000120  10 00 00 00 04 00 00 00  7f ff 04 00              |............    |
root@s217-lab00:~# /dev/shm/efivar/src/efivar -n 8be4df61-93ca-11d2-aa0d-00e098032b8c-Boot0002 -p
GUID: 8be4df61-93ca-11d2-aa0d-00e098032b8c
Name: "Boot0002"
Attributes:
	Non-Volatile
	Boot Service Access
	Runtime Service Access
Value:
00000000  08 00 00 00 a8 00 77 00  69 00 6e 00 00 00 01 04  |......w.i.n.....|
00000010  14 00 e7 75 e2 99 a0 75  37 4b a2 e6 c5 38 5e 6c  |...u...u7K...8^l|
00000020  00 cb 7f ff 04 00 02 01  0c 00 d0 41 03 0a 00 00  |...........A....|
00000030  00 00 01 01 06 00 00 17  03 12 0a 00 00 00 ff ff  |................|
00000040  00 00 04 01 2a 00 01 00  00 00 00 08 00 00 00 00  |....*...........|
00000050  00 00 00 40 06 00 00 00  00 00 d8 bc 3b 78 7d 13  |...@........;x}.|
00000060  4f 20 a4 da ac 0a 68 fd  dc aa 02 02 04 04 46 00  |O ....h.......F.|
00000070  5c 00 45 00 46 00 49 00  5c 00 4d 00 69 00 63 00  |\.E.F.I.\.M.i.c.|
00000080  72 00 6f 00 73 00 6f 00  66 00 74 00 5c 00 42 00  |r.o.s.o.f.t.\.B.|
00000090  6f 00 6f 00 74 00 5c 00  62 00 6f 00 6f 00 74 00  |o.o.t.\.b.o.o.t.|
000000a0  6d 00 67 00 66 00 77 00  2e 00 65 00 66 00 69 00  |m.g.f.w...e.f.i.|
000000b0  00 00 7f ff 04 00                                 |......          |
root@s217-lab00:~# fdisk -l
Disk /dev/sda: 111.81 GiB, 120034123776 bytes, 234441648 sectors
Disk model: GIGABYTE GP-GSTF
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 0504A1B1-B338-F043-ACD8-E5EE268ABD81

Device      Start       End   Sectors   Size Type
/dev/sda1    2048    411647    409600   200M EFI System
/dev/sda2  411648 234441614 234029967 111.6G Linux filesystem




Disk /dev/loop0: 293.38 MiB, 307625984 bytes, 600832 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
root@s217-lab00:~# ls -R /efi 
/efi:
EFI

/efi/EFI:
debian

/efi/EFI/debian:
grubx64.efi
```
The computer is an OptiPlex 7040. Full hwinfo --bios: https://lebihan.pl/files/hwinfo-bios.txt
There is also a Debian bug report where I reported info: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=963475
